version: '3.8'

services:
  api:
    build:
      context: ./
      dockerfile: Tourism.Dotnet.Parser/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres-parser
    networks:
      - my-network    
    
  postgres-parser:
    container_name: postgres-parser
    image: postgres:latest
    environment:
      POSTGRES_DB: Parser
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5439:5432"
    volumes:
      - postgres-parser-data:/var/lib/postgresql/data
    networks:
      - my-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres-auth-data:
  postgres-parser-data:
  redis_data:

networks:
  my-network:
    driver: bridge