version: '3.8'

services:
  api:
    build:
      context: ./
      dockerfile: Tourism.Dotnet.Parser/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres-parser
    networks:
      - my-network    
    environment:
      - RECOMMENDATION_SERVICE_URL=http://python-api:8000/search
    
  postgres-parser:
    container_name: postgres-parser
    image: postgres:latest
    environment:
      POSTGRES_DB: Parser
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5439:5432"
    volumes:
      - postgres-parser-data:/var/lib/postgresql/data
    networks:
      - my-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  
  python-api:
    build:
      context: ../search-endpoint
      dockerfile: Dockerfile
    container_name: recommendation-service
    ports:
      - "8000:8000"
    volumes:
      - ../search-endpoint:/app
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    working_dir: /app
    command: python run.py
    networks:
      - my-network
    restart: unless-stopped
    
volumes:
  postgres-auth-data:
  postgres-parser-data:
  redis_data:

networks:
  my-network:
    driver: bridge